import React, { FormEvent, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowLeft, ArrowRight, Check, ChevronDown, CircleCheck, Info, LockKeyhole, Menu, ShieldCheck, Sparkles, Timer, UserRound } from 'lucide-react'
import { AffordabilityInput, calculateAffordability, formatMoney, getAffordabilityBand } from './calculator'
import './styles.css'

type Step = 1 | 2 | 3 | 4
const initial: AffordabilityInput = { propertyPrice: 250000, deposit: 25000, annualIncome: 50000 }

function Header({ onStart }: { onStart: () => void }) {
  return <header><button className="brand" onClick={onStart}>Can I Buy It?</button><nav><button onClick={onStart}>Calculator</button><button onClick={() => document.getElementById('how')?.scrollIntoView({ behavior: 'smooth' })}>How it works</button><button onClick={() => document.getElementById('about')?.scrollIntoView({ behavior: 'smooth' })}>About us</button></nav><button className="menu" aria-label="Open navigation"><Menu size={22}/></button></header>
}

function Progress({ step }: { step: Step }) {
  const labels = ['Your details', 'Your result', 'Adjust', 'Get help']
  return <div className="progress" aria-label={`Step ${step} of 4`}>
    {labels.map((label, i) => <React.Fragment key={label}><div className={`progress-step ${step === i + 1 ? 'active' : ''} ${step > i + 1 ? 'done' : ''}`}><span>{step > i + 1 ? <Check size={15}/> : i + 1}</span><em>{label}</em></div>{i < 3 && <div className={`line ${step > i + 1 ? 'done' : ''}`}/>}</React.Fragment>)}
  </div>
}

function MoneyInput({ id, label, value, onChange, hint, error }: { id: string; label: string; value: number; onChange: (v: number) => void; hint?: string; error?: string }) {
  return <label className="field" htmlFor={id}><span>{label}</span><div className={`money-input ${error ? 'invalid' : ''}`}><b>£</b><input id={id} inputMode="numeric" value={value || ''} onChange={e => onChange(Number(e.target.value.replace(/\D/g, '')))} aria-invalid={!!error}/></div>{hint && <small>{hint}</small>}{error && <small className="error">{error}</small>}</label>
}

function Gauge({ value }: { value: number }) {
  const band = getAffordabilityBand(value)
  const color = { strong: '#16866f', good: '#16866f', borderline: '#d88b21', challenging: '#c64b4b' }[band]
  const pct = Math.max(4, Math.min(100, ((value - 2.5) / 3.5) * 100))
  return <div className="gauge" role="img" aria-label={`Affordability indicator: required mortgage is ${value.toFixed(1)} times annual household income. ${band} position.`}>
    <div className="gauge-arc" style={{ '--gauge': `${pct}%`, '--tone': color } as React.CSSProperties}><div className="gauge-inner"><small>{band === 'strong' ? 'Strong position' : band === 'good' ? 'Good position' : band === 'borderline' ? 'Watch closely' : 'Higher risk'}</small><strong>{value.toFixed(1)}x</strong><span>income multiple <Info size={13}/></span></div></div>
    <div className="gauge-labels"><span>Lower risk</span><span>Higher risk</span></div>
  </div>
}

function Details({ values, setValues, next }: { values: AffordabilityInput; setValues: React.Dispatch<React.SetStateAction<AffordabilityInput>>; next: () => void }) {
  const [errors, setErrors] = useState<Record<string,string>>({})
  const submit = (e: FormEvent) => { e.preventDefault(); const nextErrors: Record<string,string> = {}; if (values.propertyPrice <= 0) nextErrors.propertyPrice = 'Enter a property price'; if (values.deposit < 0) nextErrors.deposit = 'Deposit cannot be negative'; if (values.deposit >= values.propertyPrice) nextErrors.deposit = 'Deposit must be less than the property price'; if (values.annualIncome <= 0) nextErrors.annualIncome = 'Enter your annual household income'; setErrors(nextErrors); if (!Object.keys(nextErrors).length) next() }
  return <main className="details-page"><section className="intro"><div className="eyebrow">Mortgage affordability calculator</div><h1>Can I buy this<br/>property?</h1><p>Get a clear, instant indication of what you could borrow — and see how your finances stack up.</p><div className="trust-row" id="about"><div><Timer/><b>Instant results</b><span>See your position in seconds</span></div><div><ShieldCheck/><b>100% confidential</b><span>Your details stay secure</span></div><div><Sparkles/><b>No credit check</b><span>Your score won’t be affected</span></div></div></section>
    <form className="calculator-card" onSubmit={submit}><div className="card-heading"><div><span className="step-tag">STEP 1 OF 4</span><h2>Tell us about your plans</h2></div><p>It only takes a minute.</p></div><MoneyInput id="price" label="Property price" value={values.propertyPrice} onChange={v => setValues(s => ({...s, propertyPrice:v}))} error={errors.propertyPrice}/><MoneyInput id="deposit" label="Your deposit" value={values.deposit} onChange={v => setValues(s => ({...s, deposit:v}))} hint={values.propertyPrice > 0 ? `${(values.deposit / values.propertyPrice * 100).toFixed(0)}% of the property price` : ''} error={errors.deposit}/><MoneyInput id="income" label="Annual household income" value={values.annualIncome} onChange={v => setValues(s => ({...s, annualIncome:v}))} hint="Before tax, including joint income" error={errors.annualIncome}/><button className="primary" type="submit">Show my result <ArrowRight size={18}/></button><p className="secure"><LockKeyhole size={14}/> Your information stays private and secure.</p></form>
  </main>
}

function Metric({ label, value, note }: { label:string; value:string; note?:string }) { return <div className="metric"><span>{label}</span><strong>{value}</strong>{note && <small>{note}</small>}</div> }

function Results({ values, adjust, help }: { values: AffordabilityInput; adjust:()=>void; help:()=>void }) {
  const r = calculateAffordability(values); const band = getAffordabilityBand(r.incomeMultiple); const positive = band === 'good' || band === 'strong'
  return <main className="results-page"><section className="result-hero"><div className="result-copy"><div className="status-pill"><CircleCheck size={15}/> Your result is ready</div><h1>{positive ? 'Good news — this looks achievable.' : band === 'borderline' ? 'This could be within reach.' : 'This may need some adjustment.'}</h1><p>Based on the details you shared, here’s how your mortgage position looks.</p></div><Gauge value={r.incomeMultiple}/></section><section className="metrics"><Metric label="Mortgage required" value={formatMoney(r.mortgageRequired)} note="Property price minus deposit"/><Metric label="Your deposit" value={formatMoney(values.deposit)} note={`${r.depositPercentage.toFixed(0)}% of property price`}/><Metric label="Loan to value (LTV)" value={`${r.ltv.toFixed(0)}%`} note="The portion you need to borrow"/><Metric label="Income multiple" value={`${r.incomeMultiple.toFixed(1)}x`} note="Mortgage ÷ household income"/></section><div className="notice"><Info size={19}/><p><b>This is an indication, not a mortgage offer.</b><br/>Lenders have different criteria and will complete their own affordability assessment.</p></div><section className="next-card"><div><span>WANT TO IMPROVE YOUR POSITION?</span><h2>See what a few changes could do</h2><p>Adjust your deposit, price or income and watch your result update instantly.</p></div><button className="primary" onClick={adjust}>Adjust my numbers <ArrowRight size={18}/></button></section><button className="text-link" onClick={help}>Or speak to a mortgage expert <ArrowRight size={15}/></button></main>
}

function Slider({ label, value, min, max, step, onChange }: {label:string; value:number; min:number; max:number; step:number; onChange:(n:number)=>void}) { return <label className="slider"><span><b>{label}</b><strong>{formatMoney(value)}</strong></span><input type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(+e.target.value)}/><div><small>{formatMoney(min)}</small><small>{formatMoney(max)}</small></div></label> }

function Adjust({ original, values, setValues, back, help }: { original:AffordabilityInput; values:AffordabilityInput; setValues:React.Dispatch<React.SetStateAction<AffordabilityInput>>; back:()=>void; help:()=>void }) {
  const r=calculateAffordability(values), o=calculateAffordability(original)
  return <main className="adjust-page"><div className="page-title"><span className="step-tag">STEP 3 OF 4</span><h1>What could improve your position?</h1><p>Move the sliders to explore. Your result updates as you go.</p></div><div className="adjust-grid"><section className="slider-card"><h2>Adjust your numbers</h2><Slider label="Property price" value={values.propertyPrice} min={100000} max={750000} step={5000} onChange={v=>setValues(s=>({...s,propertyPrice:v,deposit:Math.min(s.deposit,v-1000)}))}/><Slider label="Your deposit" value={values.deposit} min={5000} max={Math.max(10000,values.propertyPrice*.5)} step={1000} onChange={v=>setValues(s=>({...s,deposit:v}))}/><Slider label="Annual household income" value={values.annualIncome} min={20000} max={200000} step={1000} onChange={v=>setValues(s=>({...s,annualIncome:v}))}/><button className="reset" onClick={()=>setValues(original)}>Reset to original numbers</button></section><section className="live-card"><span className="live"><i/> LIVE RESULT</span><Gauge value={r.incomeMultiple}/><div className="mini-metrics"><Metric label="Mortgage required" value={formatMoney(r.mortgageRequired)}/><Metric label="Loan to value" value={`${r.ltv.toFixed(0)}%`}/></div>{r.incomeMultiple < o.incomeMultiple && <div className="improvement"><Check size={17}/><span><b>You’ve improved your position</b>Your income multiple is down from {o.incomeMultiple.toFixed(1)}x to {r.incomeMultiple.toFixed(1)}x.</span></div>}<button className="primary" onClick={help}>Talk to an expert <ArrowRight size={18}/></button></section></div><button className="back-link" onClick={back}><ArrowLeft size={16}/> Back to my original result</button></main>
}

function Contact({ values, back }: {values:AffordabilityInput; back:()=>void}) {
  const [sent,setSent]=useState(false); const [name,setName]=useState(''); const [email,setEmail]=useState('')
  if(sent) return <main className="success"><div className="success-icon"><Check size={32}/></div><span className="step-tag">ENQUIRY SENT</span><h1>Thanks{name ? `, ${name.split(' ')[0]}` : ''}!</h1><p>We’ve received your enquiry. A mortgage expert will be in touch within one business day.</p><div className="what-next"><b>What happens next?</b><span><i>1</i>We’ll review your details</span><span><i>2</i>An expert will call you</span><span><i>3</i>You’ll explore your options</span></div><button className="secondary" onClick={back}>Back to my results</button></main>
  return <main className="contact-page"><section className="help-copy"><span className="step-tag">STEP 4 OF 4</span><h1>Let’s find the right path forward.</h1><p>Share a few details and one of our mortgage experts will get in touch to talk through your options.</p><ul><li><Check/> Whole-of-market advice</li><li><Check/> Access to thousands of mortgage deals</li><li><Check/> No obligation, just helpful guidance</li></ul><div className="quote">“Speaking to someone made everything feel much clearer.”<span>— Recent homebuyer</span></div></section><form className="contact-card" onSubmit={e=>{e.preventDefault(); if(name && email)setSent(true)}}><h2>Tell us how to reach you</h2><label>Full name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Alex Morgan"/></label><label>Email address<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="alex@example.com"/></label><label>Phone number <small>(optional)</small><input type="tel" placeholder="07123 456789"/></label><label>When are you looking to buy?<div className="select-wrap"><select defaultValue=""><option value="" disabled>Select a timeframe</option><option>As soon as possible</option><option>Within 3 months</option><option>3–6 months</option><option>6+ months</option></select><ChevronDown/></div></label><button className="primary">Send my enquiry <ArrowRight size={18}/></button><p className="secure"><LockKeyhole size={14}/> Your details are secure and never shared.</p></form></main>
}

function App(){ const [step,setStep]=useState<Step>(1); const [values,setValues]=useState(initial); const [original,setOriginal]=useState(initial); const content=useMemo(()=>{ if(step===1)return <Details values={values} setValues={setValues} next={()=>{setOriginal(values);setStep(2)}}/>; if(step===2)return <Results values={values} adjust={()=>setStep(3)} help={()=>setStep(4)}/>; if(step===3)return <Adjust original={original} values={values} setValues={setValues} back={()=>{setValues(original);setStep(2)}} help={()=>setStep(4)}/>; return <Contact values={values} back={()=>setStep(2)}/> },[step,values,original]); return <div className="app"><Header onStart={()=>{setValues(initial);setStep(1)}}/><Progress step={step}/>{content}<footer id="how"><b>Can I Buy It?</b><span>Simple answers for one of life’s biggest decisions.</span><small>Prototype only · Not financial advice</small></footer></div> }

createRoot(document.getElementById('root')!).render(<App/>)
